import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Container,
  Main,
  Footer,
  FooterLink,
  Title,
  TitleLink,
  Card,
  Description,
  CardTitle,
  CardDescription,
  Code,
  Grid,
  Logo,
  LogoImg
} from '../components/index/elements';

const Home: NextPage = () => (
  <Container>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/public/favicon.ico" />
    </Head>

    <Main>
      <Title>
        Welcome to <TitleLink href="https://nextjs.org">Next.js!</TitleLink>
      </Title>

      <Description>
        Get started by editing <Code>pages/index.tsx</Code>
      </Description>

      <Grid>
        <Card href="https://nextjs.org/docs">
          <CardTitle>Documentation &rarr;</CardTitle>
          <CardDescription>
            Find in-depth information about Next.js features and API.
          </CardDescription>
        </Card>

        <Card href="https://nextjs.org/learn">
          <CardTitle>Learn &rarr;</CardTitle>
          <CardDescription>
            Learn about Next.js in an interactive course with quizzes!
          </CardDescription>
        </Card>

        <Card href="https://github.com/vercel/next.js/tree/canary/examples">
          <CardTitle>Examples &rarr;</CardTitle>
          <CardDescription>
            Discover and deploy boilerplate example Next.js projects.
          </CardDescription>
        </Card>

        <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
          <CardTitle>Deploy &rarr;</CardTitle>
          <CardDescription>
            Instantly deploy your Next.js site to a public URL with Vercel.
          </CardDescription>
        </Card>
      </Grid>
    </Main>

    <Footer>
      <FooterLink
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <Logo>
          <LogoImg src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </Logo>
      </FooterLink>
    </Footer>
  </Container>
);

export default Home;
